# Generated by Django 4.2.7 on 2023-12-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_portal_code_useraddress_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='initial_deposite_date',
            new_name='initial_deposit_date',
        ),
    ]
